spring:
  datasource:
    name: spring_boot_mybatis
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_redis?useSSL=FALSE&allowMultiQueries=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: '!@#$1234Abcd'
    tomcat:
      max-wait: 10000
      max-active: 300
      test-on-borrow: true
  devtools:
    restart:
      enabled: true
      additional-paths: mapper
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.niu.springbootredis.model
  cache-enabled: true
  default-statement-timeout: 10000
  map-underscore-to-camel-case: true
  use-generated-keys: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.niu.springbootredis.mapper: debug
